use doxygen module only when compiling older version of lammps with gcc/8.4.0 on Rocky 9. FOr a newer version, get linker errors undefined reference to std::__cxx11::basic_stringstream which result from mixing different values for the _GLIBCXX_USE_CXX11_ABI macro that comes from different versions of the compiler. The latter version of lammps uses gcc 11 and  system doxygen, tere is no conflict.